apiVersion: v1
kind: ResourceQuota
metadata:
  name: example
  namespace: openshift-monitoring
spec:
  hard:
    pods: '4'
    requests.cpu: '1'
    requests.memory: 500Mi
    limits.cpu: '2'
    limits.memory: 500Mi

